name: flutter_sinusoidals_v2
description: >-
  A flutter package that helps you to visualize sine waves as you desire.
  All basic waves are already supported, plus customized waves & some pre-defined waves.
version: 0.2.0
homepage: https://github.com/amehroz-mufin/flutter_sinusoidals/

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
